username_textbox_locator=id===cust_user_id
password_textbox_locator=id===passwd
loginBtn_locator=xpath===//button[contains(text(),'Log In')]
logoutBtn_locator=xpath===(//div[contains(@class,'profile-menu')])[1]

sideBarMenu=xpath===//span[contains(text(),'#menu#')]

assetName=xpath===//table[@class='table']/thead/following::tbody/tr/td[contains(text(),'#value#')]
cityNameFromDropdown=xpath===//div[@role='listbox']/child::div[contains(text(),'#value#')]
viewDetailsPopupForModule=xpath===(//table)[2]//tbody/tr/td/span[contains(text(),'#value#')]
viewDetailsPopupForModuleCreatedDate=xpath===((//table)[2]//tbody/tr/td/span[contains(text(),'#value#')])[1]
viewDetailsPopupForModuleUpdatedDate=xpath===((//table)[2]//tbody/tr/td/span[contains(text(),'#value#')])[2]
playerStatusOnTeamVerificationPopup=xpath===(//table)[2]//tbody/tr/td/div/div[contains(text(),'#value#')]
playerInactiveStatusOnTeamVerificationPopup=xpath===//*[contains(text(),'Non-Active Players')]/following::*[contains(text(),'#value#')]
playersOnSelectPlayerPopupForTournament=xpath===//*[contains(text(),'#value#')]
tournamentOnCreateMatchPopup=xpath===//select//option[contains(text(),'#value#')]
playerOnPlayerPage=xpath===//table//tbody/tr/td[contains(text(),'#value#')]
matchListOnDashboardPage=xpath===//div[contains(text(),'#value1#')]/following-sibling::div/child::table/tbody/tr/td[contains(text(),'#value2#')]
liveMatchPageData=xpath===//table[@class='table']/child::tbody/child::tr/td[contains(text(),'#value#')]
venueEditBtn=xpath===//td[contains(text(),'#value#')]/following-sibling::td/child::i[@title='Edit']
managerIDText=xpath===//table//tbody//tr//td[contains(text(),'#value#')]/following::td[position()=1]
agentIDText=xpath===//table//tbody//tr//td[contains(text(),'#value#')]/following::td[position()=1]
managerInMatchAssignManagerDropdown=xpath===//label[contains(text(),'#agentName#')]/..//input
managerCheckboxByManagerName=xpath===//label[normalize-space(text())='#value#']/preceding-sibling::input[@type='checkbox']
assignManagerDropdownCheckbox=xpath===//td[contains(text(),'#matchDate#')]//..//div[@role='menu']/child::div[#index#]/child::input
assignManagerDropdown=xpath===//td[contains(text(),'#matchDate#')]//..//div[@class='dropdown-wrapper']/child::button
todayMatch=xpath===(//td[contains(text(),'#matchName#')])[1]
tomorrowMatch=xpath===(//td[contains(text(),'#matchName#')])[2]
upcomingMatch=xpath===(//td[contains(text(),'#matchName#')])[3]
viewDetailBtnOnAgentUI=xpath===//a[contains(text(),'View Detail')]
liveMatchModule=xpath===//span[contains(text(),'Live Matches')]
viewDetailOnAgentUI=xpath===//a[contains(text(),'View Detail')]
toss=xpath===//p[contains(text(),'Toss Will Take Place Shortly')]
headToss=//button[contains(text(),'HEAD')]
tailToss=//button[contains(text(),'TAIL')]
teamATossSelection=(//button[@class='btn btn-outline-secondary me-2 rounded'])[2]
teamATossResult=(//button[@class='btn btn-outline-secondary me-2 rounded'])[3]
teamBTossSelection=(//button[@class='btn btn-outline-secondary rounded'])[2]
teamBTossResult=(//button[@class='btn btn-outline-secondary rounded'])[3]
select11PlayerBtn=//button[contains(text(),'Select 11 Players')]
saveBtn=//button[contains(text(),'Save')]
runBtn=//div[@class='ball-action-sec']//div[@class='runs-bx']//button[contains(text(),'#run#')]
bowledBtn=//button[contains(text(),'BOWLED')]
declareBtn=//button[contains(text(),'DECLARE INNING')]
battingPlayers=(//button[@title='Select for batting'])[#index#]
firstBattingPlayers=(//div[@class='playerlist']//button[@class='playersname px-2 mx-1'])[1]
secondBattingPlayers=(//div[@class='playerlist']//button[@class='playersname px-2 mx-1'])[2]
bowlingPlayers=(//button[@title='Select bowler'])[#index#]
firstBowlingPlayers=(//div[@class='playerlist']//button[@class='playersname px-2 mx-1'])[12]
secondBowlingPlayers=(//div[@class='playerlist']//button)[2]
teamAViewBtn=(//button[contains(text(),'View')])[1]
teamBViewBtn=(//button[contains(text(),'View')])[2]
teamHideBtn=//button[contains(text(),'Hide')]
startBallBtn=//button[contains(text(),'Ball Start')]
winningTeamOnMatchHistory=xpath===//div[@class='match_status' and contains(text(),'#teamName#')]
pageHeading=xpath===//h2[contains(text(),'#pageName#')]
venueDeleteBtn=xpath===(//td[contains(text(),'#venueName#')]//following::td)[6]//child::i[@title='Delete']
moduleData=xpath===//td[contains(text(),'#name#')]
loginForm=xpath===//h3[contains(text(),'Login to Dashboard')]//parent::div
checkbox=xpath===//label[contains(text(),'#managerName#')]/..//child::input[contains(@id,'agent-checkbox')]

//VenueErrorMessage
nameField=Venue Name Is Required
countryField=Country Is Required
stateField=State Is Required
cityField=City Is Required
imageField=Image Is Required
nameWithMaxLength=Venue Name Cannot Exceed 60 Characters.

//TeamErrorMessages
duplicateTeamName=Failed to create team
teamNameField=Team name is required.

//AutomationVenueNameWithThirtyCharacter
maxLength=AutomationModuleNameWithThirtyCharacter_AutomationModuleNameWithThirtyCharacter

//TournamentValidationMsg
delete_msg=Schedule Deleted Successfully
success_msg=Schedule Created Successfully
selectPlayer_error_msg=Each Team Must Have A Minimum Of 11 And A Maximum Of 20 Active Players.
bothDateInPast=Cannot Edit Dates That Are Both In The Past.
startDateLessThenEndDate=Start Date Cannot Be After End Date.

//ManagerMobileNoValidationMessages
no_number=Mobile Number Is Required
less_then_10=Mobile Number Must Be 10 Digits
